steps: 100
grid_size: [10, 10]
start_pos: [1, 1]
target_pos: [8, 8]
obstacles:
  - [3, 3]
  - [4, 4]
  - [5, 5]
  - [6, 8]
  - [2, 7]
  - [2, 4]
  - [3, 6]
  - [7, 7]
  - [8, 7]
  - [9, 2]
sensor_range: 4